### PR TITLE
Add basic UI 

### PR DESCRIPTION
**Pull request by Bria222**
# In this project I:
 - Created a app.rb file that will serve as console app entry-point. by:

- List all books.

- List all people.

- Create a person (teacher or student, not a plain Person).

- Create a book.

- Create a rental.

- List all rentals for a given person id.

## defined the entry point, in main.rb file which is a method called main that is invoked at the end of the file. The method do the following:

- Present the user with a list of options to perform.
- 
- Lets users choose an option.
- 
- If needed, ask for parameters for the option.
- 
- Have a way to quit the app.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @Bria222,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## **Invalid Code Review Request**

You have submitted a project, that _**Your app is not working, please make sure you follow the microverse curriculum for this project once your app is working re-submit for review.**_

Capture d’écran 2022-09-30 141325
Capture d’écran 2022-09-30 141346


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Bria222** [comment]
@dasileker i have debugged my code its now working fine 
Screenshot (6)

**Comment by Bria222** [comment]
@dasileker i have debugged my code its now working fine 
Screenshot (6)

**Comment by dasileker** [comment]
Please send it back for review

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
